# ~/.bashrc: executed by bash(1) for non-login shells.

# Note: PS1 and umask are already set in /etc/profile. You should not
# need this unless you want different defaults for root.
# PS1='${debian_chroot:+($debian_chroot)}\h:\w\$ '

shopt -s histappend
shopt -s cdspell
shopt -s globstar
shopt -s checkwinsize

set -o ignoreeof
set -b

umask 022

if [ -f /etc/bash_completion ]; then
     . /etc/bash_completion
fi

export CDPATH='.:/opt:/opt/CommProve:/media/sf_Shared/:/media/sf_Shared/GitHub/'

export HISTIGNORE="&:[bf]g:exit"

HISTSIZE=10000
HISTFILESIZE=10000

export TERM=xterm-256color

# You may uncomment the following lines if you want `ls' to be colorized:

export LS_OPTIONS='--color=auto'
export COLUMNS

eval "`dircolors`"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'

# Some more alias to avoid making mistakes:

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'  

# Prompt

export PS1='\u :: \[\033[1;32m\]$(/usr/local/bin/git-prompt path)\[\033[0m\]$(/usr/local/bin/git-prompt git) -> '

# Keep synchronized history...

export PROMPT_COMMAND='history -a'

trap 'echo Exit $?' ERR
